name: PyroBlack latest-boost (t.me/tgLibs) Benchmark Testing Tool

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - runfile
    tags-ignore:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v4

      - name: Setup Python Version
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run script
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN3 }}
          TG_SESSION: ${{ secrets.TG_SESSION3 }}
          TG_FLOOD_SLEEP_THRESHOLD: ${{ secrets.TG_FLOOD_SLEEP_THRESHOLD }}
          TG_MESSAGE_LINK: ${{ secrets.TG_MESSAGE_LINK }}
        run: |
          echo "Beginning Pyrogram test"
          mkdir -p outputs
          pip install --force-reinstall uvloop pyroblack tgcrypto-pyroblack > /dev/null 2>&1
          P=$(python scripts/python/p2.py)
          pip uninstall -y pyroblack TgCrypto-pyroblack > /dev/null 2>&1
          echo "${P}" > outputs/pyroblack-latest-boost.json

      - name: Commit and push changes
        run: |
          git config pull.rebase true
          git config user.email "41898282@users.noreply.github.com"
          git config user.name "GitHub Actions <PyroBlack>"
          git add outputs/ -A
          git commit -m "update PyroBlack bench"
          git pull origin master
          git push origin master
